In [87]:
import numpy as np
import matplotlib.pyplot as plt

n = 4
A = 2 * np.eye(n) - np.eye(n, k=1) - np.eye(n, k=-1)

def Jacobi_Rotation(A,j,k):
    R = np.eye(n)
    if A[j,j] == A[k,k]:
        theta = np.pi / 4
        R[j, j], R[j, k], R[k, j], R[k, k] = np.cos(theta), -np.sin(theta), np.sin(theta), np.cos(theta)   
    else:       
        tau = (A[j,j] - A[k,k]) / (2 * A[j,k]) # ctg(2a)
        tg = np.sign(tau) / (abs(tau) + np.sqrt(1 + tau**2)) # tg(a)
        cos = 1 / np.sqrt(1 + tg**2) # cos(a)
        sin = cos * tg # sin(a)
        R[j, j], R[j, k], R[k, j], R[k, k] = cos, -sin, sin, cos
    S = np.dot(np.transpose(R), np.dot(A,R))
    return S

def Jacobi(A):
    while True:
        for j in range(0,n-1):
            for k in range(j+1,n):
                A = Jacobi_Rotation(A,j,k)
                if (np.linalg.norm(A - np.diag(np.diag(A))) < 10**-6):
                    return A
                
print(A, "\n")       
print(Jacobi(A), "\n")
print(np.diag(Jacobi(A)), "\n")
print(np.linalg.eigvals(A))

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]] 

[[ 3.81966011e-01  5.90604092e-08  5.02580446e-09 -2.04540255e-12]
 [ 5.90604092e-08  3.61803399e+00  4.64663860e-11 -5.05591173e-17]
 [ 5.02580450e-09  4.64665020e-11  2.61803399e+00  0.00000000e+00]
 [-2.04543464e-12 -1.76096303e-16  1.09360000e-16  1.38196601e+00]] 

[0.38196601 3.61803399 2.61803399 1.38196601] 

[3.61803399 2.61803399 0.38196601 1.38196601]
