In [257]:
# (Note this can readily fail if A has an integer eigenvalue.)
# Rayleigh Quotient Iteration
# Input: square numpy array A, (nonzero) 1d numpy array x, shift s, steps k
# Output: eigenvalue lam and eigenvector x

from numpy import *

def rqi( A, x, k ):
	I = eye(A.shape[0])
	for j in range(k):
		u = x/linalg.norm(x)		# normalize
		lam = dot(u,dot(A,u))		# Rayleigh quotient
#		print j,u, lam
#		print A-lam*I
		x = linalg.solve(A-lam*I,u)	# inverse power iteration
	u = x/linalg.norm(x)
	lam = dot(u,dot(A,u))
	return lam,x/linalg.norm(x,inf)

# try it out
#A = array([[11.,-12,-6],[5,-5,-4],[-1,0,3]])
#A = random.random((3,3))
A = 2*np.eye(10)-np.eye(10, k=1)-np.eye(10,k=-1)
for i in range(1):
	x = random.rand(10)-0.5; lam,v = rqi( A, x, 1000 ); print (lam,v)
    
linalg.eig(A)

3.3097214678905704 [ 0.76352112 -1.          0.54620035  0.28462968 -0.91898595  0.91898595
 -0.28462968 -0.54620035  1.         -0.76352112]


(array([3.91898595, 3.68250707, 3.30972147, 2.83083003, 2.28462968,
        1.71537032, 0.08101405, 0.31749293, 0.69027853, 1.16916997]),
 array([[ 0.12013117,  0.23053002,  0.3222527 ,  0.38786839, -0.42206128,
          0.42206128, -0.12013117,  0.23053002, -0.3222527 , -0.38786839],
        [-0.23053002, -0.38786839, -0.42206128, -0.3222527 ,  0.12013117,
          0.12013117, -0.23053002,  0.38786839, -0.42206128, -0.3222527 ],
        [ 0.3222527 ,  0.42206128,  0.23053002, -0.12013117,  0.38786839,
         -0.38786839, -0.3222527 ,  0.42206128, -0.23053002,  0.12013117],
        [-0.38786839, -0.3222527 ,  0.12013117,  0.42206128, -0.23053002,
         -0.23053002, -0.38786839,  0.3222527 ,  0.12013117,  0.42206128],
        [ 0.42206128,  0.12013117, -0.38786839, -0.23053002, -0.3222527 ,
          0.3222527 , -0.42206128,  0.12013117,  0.38786839,  0.23053002],
        [-0.42206128,  0.12013117,  0.38786839, -0.23053002,  0.3222527 ,
          0.3222527 , -0.42206128, -0.12013

In [255]:
"""
Sample code for Rayleigh quotient iteration applied to 
shift matrix.
"""

from pylab import *

A = array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]])

print "\nA = "
print A

lam,X = eig(A)

print "\nEigenvalues: ",lam

v = randn(4)
print "\nStarting guess v: ",v
print " "

mu = 1. + 1j
print "k = %s, mu = %21.16f + %21.16fj" %  (0,mu.real,mu.imag)

for k in range(1,10):
    B = A - mu*eye(4)
    try:
        w = solve(B,v)
    except:
        print "Matrix is singular!   Converged solution"
        break
    v = w / norm(w,2)
    mu = dot(conj(v.T), dot(A,v))
    print "k = %s, mu = %21.16f + %21.16fj" %  (k,mu.real,mu.imag)


SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nA = ")? (<ipython-input-255-331f0b8016e6>, line 10)

In [266]:
import numpy as np


def RayleighQuotientIteration(A, max_iter):
    I = np.identity(A.shape[0])
    v = np.random.randn(A.shape[0])
    v /= np.linalg.norm(v) #generate a uniformly random unit vector
    mu = np.dot(v, np.dot(A, v))
    for t in range(max_iter):
        v = np.linalg.solve(A - mu * I, v) #compute (mu*I - A)^(-1)v
        v /= np.linalg.norm(v)
        mu = np.dot(v, np.dot(A, v))/np.dot(v,v) #compute Rayleigh quotient
    return (v, mu)

A = 2*np.eye(10)-np.eye(10, k=1)-np.eye(10,k=-1)

print(RayleighQuotientIteration(A, 1000))

np.linalg.eigvals(A)


(array([ 0.42206128,  0.12013117, -0.38786839, -0.23053002,  0.3222527 ,
        0.3222527 , -0.23053002, -0.38786839,  0.12013117,  0.42206128]), 1.7153703234534299)


array([3.91898595, 3.68250707, 3.30972147, 2.83083003, 2.28462968,
       1.71537032, 0.08101405, 0.31749293, 0.69027853, 1.16916997])

In [263]:
np.shape([0, 1, 2, 3])

(4,)