In [46]:
import numpy as np
import random

def mult_matrix(m1, m2):
    sum = 0
    temp = []
    m3 = []
    if len(m1[0]) != len(m2):
        print("Матрицы нельзя перемножить")
    else:
        r1 = len(m1)
        c1 = len(m1[0])
        r2 = c1
        c2 = len(m2[0])
        for i in range(r1):
            for j in range(c2):
                for k in range(c1):
                    sum += m1[i][k] * m2[k][j]
                temp.append(sum)
                sum = 0
            m3.append(temp)
            temp = []
    return m3
            
    
def create_matrix(m, n):
    a = []
    b = []
    for i in range(m):
        for j in range(n):
            b.append(random.randint(1,10))
        a.append(b)
        b = []
    return a

m1 = create_matrix(3, 4)
m2 = create_matrix(4, 2)           

print('1 матрица: ')
print(np.array(m1))
print('2 матрица: ')
print(np.array(m2))
print('Произведение матриц: ')
print(mult_matrix(m1, m2))
print('Произведение матриц с помощью numpy: ')
print(np.matrix(m1)*np.matrix(m2))


1 матрица: 
[[ 5  8 10  8]
 [10  6  5  8]
 [ 4  5  9  4]]
2 матрица: 
[[4 2]
 [5 7]
 [6 8]
 [6 9]]
Произведение матриц: 
[[168, 218], [148, 174], [119, 151]]
Произведение матриц с помощью numpy: 
[[168 218]
 [148 174]
 [119 151]]
